spring:
  application:
    name: spring-cloud-ribbon
  zipkin:
    base-url: http://121.43.162.28:9411

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://121.43.162.28:8761/eureka/