spring:
  application:
    name: spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://121.43.162.28:8761/eureka/

management: 
  metrics:
    web:
      server:
        auto-time-requests: false