spring:
  application:
    name: spring-cloud-config

server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8760/eureka/,http://${eureka.instance.hostname}:8761/eureka/
  instance:
    ip-address: 121.43.162.28
    hostname: 121.43.162.28
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}