spring:
  application:
    name: spring-cloud-monitor

server:
  port: 9696

turbine:
  appConfig: spring-cloud-ribbon,spring-cloud-feign  #配置Eureka中的serviceId列表，表明监控哪些服务
  aggregator:
    clusterConfig: default  #需要监控的服务集群名
  clusterNameExpression: new String("default")
  combine-host-port: true
