---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
  zipkin:
    base-url: http://121.43.162.28:9411    
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #表示是否将自己注册到Eureka Server，默认为true
    fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:8771/eureka/,http://localhost:8781/eureka/
      
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
  zipkin:
    base-url: http://121.43.162.28:9411    
server:
  port: 8771

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #表示是否将自己注册到Eureka Server，默认为true
    fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8781/eureka/ 

---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
  zipkin:
    base-url: http://121.43.162.28:9411    
server:
  port: 8781

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #表示是否将自己注册到Eureka Server，默认为true
    fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8771/eureka/           