---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer0
  
server:
  port: 8760

eureka:
  instance:
    ip-address: 121.43.162.28 # 指定此实例的ip
    hostname: 121.43.162.28
    prefer-ip-address: true #注册时使用ip而不是主机名
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
  client:
    registerWithEureka: true #表示是否将自己注册到eureka server，因为要构建集群环境，需要将自己注册到及群众，所以应该开启。默认为true，可不设置
    fetchRegistry: true #表示是否从eureka server获取注册信息，如果是单一节点，不需要同步其他eureka server节点，则可以设置为false，但此处为集群，应该设置为true，默认为true，可不设置
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
  
server:
  port: 8761

eureka:
  instance:
    ip-address: 121.43.162.28 # 指定此实例的ip
    hostname: 121.43.162.28
    prefer-ip-address: true #注册时使用ip而不是主机名
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
  client:
    registerWithEureka: true #表示是否将自己注册到eureka server，因为要构建集群环境，需要将自己注册到及群众，所以应该开启。默认为true，可不设置
    fetchRegistry: true #表示是否从eureka server获取注册信息，如果是单一节点，不需要同步其他eureka server节点，则可以设置为false，但此处为集群，应该设置为true。默认为true，可不设置
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8760/eureka/