spring:
  application:
    name: spring-cloud-client

server:
  port: 8762
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://121.43.162.28:8760/eureka/,http://121.43.162.28:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}