server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
#---
#server:
#  port: 8888
#spring:
#  profiles: peer0
#---
#server:
#  port: 9999
#spring:
#  profiles: peer1