spring:
  application:
    name: spring-cloud-config-server
  zipkin:
    base-url: http:/121.43.162.28:9411
        
  cloud:
    config:
      enabled: true
      label: master
      server:
        git:
          uri: https://github.com/love-somnus/SpringCloud
          search-paths: config-repository
          username: love-somnus
          password: miss332512
          
server:
  port: 8888

#加入注册中心，实现高可用
eureka:
  client:
    serviceUrl:
      defaultZone: http://121.43.162.28:8761/eureka/
