spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      enabled: true
      label: master
      server:
        git:
          uri: https://github.com/love-somnus/spring-cloud-config
          search-paths: respo
          username: love-somnus
          password: miss332512
          
server:
  port: 8888

#加入注册中心，实现高可用
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
