spring:
  application:
    name: spring-cloud-admin-client
  zipkin:
    base-url: http:/121.43.162.28:9411
        
  boot:
    admin:
      client:
        url: http://localhost:8084
          
server:
  port: 8085

#加入注册中心，实现高可用
eureka:
  client:
    serviceUrl:
      defaultZone: http://121.43.162.28:8761/eureka/
